language: generic
script: bash ./deploy.sh

# This is the Official Way to get travis to run a 14.04 build.
# We need sudo to install texlive-xelatex for the pdf.
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - pandoc
    - pandoc-citeproc
    - texlive-xelatex

env:
  global:
  - ENCRYPTION_LABEL: ebc0f2213c37
  - COMMIT_AUTHOR_EMAIL: "katriel.cohn-gordon@cs.ox.ac.uk"
